---

language: python
python: "2.7"

install:
  - pip install ansible

script:
  - ansible-playbook -i inventory.ini -c local tests/site.yml
  - ansible-playbook -i inventory.py -c local tests/site.yml
